import Link from 'next/link';

const cats=[['🎮','Oyun','YENİ'],['💻','Bilgisayar',''],['📱','Telefon',''],['🎮','Konsol',''],['💎','Koleksiyon',''],['🎧','Elektronik',''],['🕹️','Nadir Oyun Itemleri',''],['🛋️','Ev & Yaşam','']];
const products=[
 {t:'ASUS ROG Strix RTX 4070 Ti',p:'24.750 TL',b:38,time:'00:02:45',img:'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=700&q=80'},
 {t:'iPhone 15 Pro Max 256GB',p:'32.100 TL',b:42,time:'00:05:12',img:'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=700&q=80'},
 {t:'★ Karambit | Doppler (FN) – CS2',p:'18.250 TL',b:67,time:'00:01:33',img:'https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?auto=format&fit=crop&w=700&q=80'},
 {t:'PlayStation 5 Digital Edition',p:'15.750 TL',b:29,time:'00:10:21',img:'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=700&q=80'},
 {t:'Rolex Submariner Date',p:'126.500 TL',b:31,time:'00:07:44',img:'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=700&q=80'}
];
function Logo(){return <Link href="/" className="kk-logo"><span className="kk-mark">K</span><span><b>KAPIŞKAPIŞ</b><small>AÇIK ARTIRMA PLATFORMU</small></span></Link>}
export default function Home(){return <main className="kk-page">
<header className="kk-header"><Logo/><div className="kk-search">Ürün, kategori veya marka ara… <b>⌕</b></div><nav><Link className="active" href="/">Ana Sayfa</Link><Link href="/kategori/oyun">Kategoriler</Link><Link href="/canli">Canlı Açık Artırmalar</Link><Link href="/nasil-calisir">Nasıl Çalışır?</Link><Link href="#">Hakkımızda</Link></nav><div className="kk-actions"><button>♡<i>12</i></button><button>♢<i>3</i></button><Link href="/profil" className="ghost">Giriş Yap</Link><Link href="/ilan-olustur" className="orange">Kayıt Ol</Link></div></header>
<div className="kk-layout"><aside className="kk-side"><section><h3>Kategoriler</h3>{cats.map(([i,n,b])=><Link href={'/kategori/'+n.toLowerCase().replaceAll(' ','-')} key={n}><span>{i}</span>{n}{b&&<em>{b}</em>}</Link>)}<Link href="/kategori/tumu">Tüm Kategoriler <b>›</b></Link></section><section className="sellbox"><h3>İlan Ver</h3><p>Ürününü açık artırmayla binlerce kişiye ulaştır.</p><Link href="/ilan-olustur">Ücretsiz İlan Ver <b>⊕</b></Link></section><section className="trustbox"><p>🛡️ <b>Güvenli Alışveriş</b><small>Alıcı Koruma Sistemi</small></p><p>✹ <b>Doğrulanmış Satıcılar</b><small>%100 Güvenli</small></p></section></aside>
<section className="kk-main"><div className="hero"><div className="hero-copy"><h1>En iyi teklifler,<br/>en hızlı şekilde<br/><span>KAPIŞKAPIŞ’ta!</span></h1><p>Binlerce ürüne teklif verin,<br/>en uygun fiyatlarla kazanın.</p><div className="hero-badges"><span>🛡️ Güvenli Ödeme</span><span>✹ Doğrulanmış Satıcılar</span><span>🔒 Alıcı Koruması</span></div></div><img src="/kapiskapis-hero.jpg" alt="KapışKapış"/></div>
<div className="titleline"><h2>Şu An Kapışılanlar <span>● Canlı</span></h2><Link href="/canli">Tümünü Gör</Link></div><div className="auction-row">{products.map((x,i)=><Link href={'/urun/'+(i+1)} className="auction-card" key={x.t}><div className="cardtop"><b>CANLI</b><span>◷ {x.time}</span></div><img src={x.img} alt=""/><h3>{x.t}</h3><div className="bidmeta"><small>Güncel Teklif<strong>{x.p}</strong></small><small>Teklif Sayısı<strong>{x.b}</strong></small></div><button>Teklif Ver</button></Link>)}<div className="lastminute"><h2>Son Dakika<br/>Fırsatları ⚡</h2><p>Sürenin bitmesine az kaldı!</p><button>Kaçırma!</button><div><b>00</b>:<b>12</b>:<b>45</b></div></div></div>
<div className="feature-strip">{[['⚒','Nasıl Çalışır?','Ürün bul, teklif ver, kazanmanın keyfini çıkar!'],['🛡️','Alıcı Koruması','Güvenli ödeme ve iade garantisi ile için rahat olsun.'],['📈','Satıcı Avantajları','Kolay ilan verin, ürünlerinizi daha hızlı satın.'],['🔒','Güvenli Ödeme','Ödemeniz güvence altında, ürün gelmeden ödeme.']].map(x=><div><i>{x[0]}</i><p><b>{x[1]}</b><span>{x[2]}</span><em>Detayları Gör ›</em></p></div>)}</div>
<div className="featured"><h2>Öne Çıkan Ürünler</h2><div>{products.slice(0,5).map(x=><img src={x.img} alt=""/>)}</div></div>
<div className="stats"><b>🏅 <span>10.000+</span><small>Aktif Kullanıcı</small></b><b>🛡️ <span>5.000+</span><small>Günlük Ürün</small></b><b>💼 <span>50.000+</span><small>Başarılı Teklif</small></b><b>◔ <span>7/24</span><small>Canlı Destek</small></b><div><strong>Fırsatları Kaçırma!</strong><small>En iyi teklifler için bültenimize abone olun.</small></div><input placeholder="E-posta adresiniz"/><button>Abone Ol</button></div>
</section></div>
<footer className="kk-footer"><Logo/><div><b>Kurumsal</b><a>Hakkımızda</a><a>Kariyer</a><a>Basın</a></div><div><b>Destek</b><a>Yardım Merkezi</a><a>Gizlilik Politikası</a><a>Kullanım Şartları</a></div><div><b>Hesabım</b><a>Giriş Yap</a><a>Kayıt Ol</a><a>Şifremi Unuttum</a></div><div className="newsletter"><b>Bültenimize Abone Olun!</b><p>En yeni fırsatlardan haberdar olun.</p><input placeholder="E-posta adresiniz"/><button>Abone Ol</button></div></footer>
</main>}
