export type EquipmentTaxonomy = { name: string; description: string; types: string[]; brands: string[]; specs: string[] };

export const equipmentTaxonomies: Record<string, EquipmentTaxonomy> = {
  "gaming-klavye": { name: "Gaming Klavye", description: "Form, switch ve bağlantı türüne göre oyuncu klavyeleri.", types: ["Tam Boy", "TKL", "%75", "%65", "%60", "Low Profile", "Mekanik", "Manyetik / Hall Effect", "Membran", "Hot-Swap"], brands: ["Logitech G", "Razer", "SteelSeries", "Corsair", "HyperX", "ASUS ROG", "MSI", "Akko", "MCHOSE", "Aula", "Keychron", "Glorious", "Wooting", "GamePower", "Rampage", "Havit"], specs: ["Kablolu", "2.4 GHz", "Bluetooth", "Türkçe Q", "Red Switch", "Blue Switch", "Brown Switch", "Rapid Trigger", "RGB / ARGB", "Bilek Desteği"] },
  "gaming-mouse": { name: "Gaming Mouse", description: "Oyun türü, tutuş ve sensör özelliklerine göre mouse modelleri.", types: ["FPS Mouse", "MOBA / MMO Mouse", "Ultra Hafif", "Ergonomik", "Simetrik", "Sağ El", "Mini / Small", "Dikey Mouse"], brands: ["Logitech G", "Razer", "SteelSeries", "Pulsar", "Glorious", "MCHOSE", "ASUS ROG", "Corsair", "HyperX", "Zowie", "Lamzu", "Endgame Gear", "GravaStar", "MSI", "GamePower", "Rampage"], specs: ["Kablolu", "2.4 GHz", "Bluetooth", "8K Polling", "30K+ DPI", "Optik Switch", "50 g altı", "50–70 g", "Şarj İstasyonlu"] },
  "gaming-mousepad": { name: "Gaming Mousepad", description: "Yüzey karakteri, ölçü ve taban yapısına göre mousepadler.", types: ["Control", "Speed", "Hybrid", "Cam Mousepad", "Kumaş", "Sert Yüzey", "RGB Mousepad", "Bilek Destekli"], brands: ["SteelSeries", "Razer", "Logitech G", "Zowie", "Artisan", "Pulsar", "Glorious", "Corsair", "HyperX", "ASUS ROG", "X-raypad", "GamePower", "Rampage"], specs: ["Small", "Medium", "Large", "XL", "XXL / Deskmat", "Dikişli Kenar", "Kaymaz Taban", "Yıkanabilir"] },
  "gaming-kulaklik": { name: "Gaming Kulaklık", description: "Platform, bağlantı ve ses yapısına göre oyuncu kulaklıkları.", types: ["Kulak Üstü", "Kulak İçi", "Açık Tasarım", "Kapalı Tasarım", "Konsol Kulaklığı", "E-spor Kulaklığı"], brands: ["SteelSeries", "HyperX", "Logitech G", "Razer", "Corsair", "ASUS ROG", "Sony INZONE", "JBL Quantum", "Sennheiser / EPOS", "Beyerdynamic", "Astro", "Turtle Beach", "MSI", "Rampage"], specs: ["Kablolu", "2.4 GHz", "Bluetooth", "Çift Bağlantı", "7.1 Surround", "Spatial Audio", "Çıkarılabilir Mikrofon", "Aktif Gürültü Engelleme"] },
  "gaming-monitor": { name: "Gaming Monitör", description: "Panel, çözünürlük ve yenileme hızına göre oyuncu monitörleri.", types: ["Fast IPS", "OLED / QD-OLED", "VA", "Mini LED", "Düz", "Kavisli", "UltraWide", "Dual Mode"], brands: ["ASUS ROG / TUF", "Samsung Odyssey", "LG UltraGear", "MSI", "AOC / AGON", "ViewSonic", "Gigabyte / AORUS", "Lenovo Legion", "Dell Alienware", "BenQ Zowie", "Acer Predator", "Philips Evnia", "Cooler Master"], specs: ["Full HD", "QHD / 2K", "UWQHD", "4K UHD", "144–180 Hz", "200–240 Hz", "360 Hz", "480 Hz+", "1 ms altı", "G-SYNC", "FreeSync"] },
  "bilgisayar-kasasi": { name: "Bilgisayar Kasası", description: "Anakart ve ekran kartı uyumuna göre oyuncu kasaları.", types: ["Full Tower", "Mid Tower", "Mini Tower", "Dual Chamber", "Panoramik", "Mesh Ön Panel", "Sessiz Kasa", "Mini-ITX"], brands: ["Corsair", "NZXT", "Cooler Master", "Lian Li", "Fractal Design", "ASUS ROG / TUF", "MSI", "Thermaltake", "Phanteks", "be quiet!", "DeepCool", "Xigmatek", "GameBooster", "Rampage", "Vento"], specs: ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX", "Dikey GPU", "Temperli Cam", "ARGB", "Fansız", "PSU Dahil"] },
  "ekran-karti": { name: "Ekran Kartı", description: "GPU ailesi, bellek ve soğutucu tasarımına göre ekran kartları.", types: ["NVIDIA GeForce RTX", "AMD Radeon RX", "Intel Arc", "2 Fanlı", "3 Fanlı", "Sıvı Soğutmalı", "Düşük Profil", "Creator / Workstation"], brands: ["ASUS", "MSI", "Gigabyte / AORUS", "Zotac", "Palit", "Gainward", "PNY", "Inno3D", "Sapphire", "PowerColor", "XFX", "ASRock", "Intel", "NVIDIA Founders Edition"], specs: ["8 GB", "12 GB", "16 GB", "20 GB+", "GDDR6", "GDDR7", "Ray Tracing", "DLSS", "FSR", "PCIe 4.0", "PCIe 5.0"] },
  ssd: { name: "SSD", description: "Arabirim, hız, kapasite ve kullanım senaryosuna göre SSD modelleri.", types: ["NVMe M.2", "SATA 2.5 inç", "Harici SSD", "Soğutuculu M.2", "PlayStation 5 Uyumlu", "Taşınabilir Gaming SSD"], brands: ["Samsung", "WD_BLACK", "Kingston", "Crucial", "Kioxia", "Seagate", "Corsair", "SanDisk", "Lexar", "ADATA XPG", "TeamGroup", "MSI Spatium", "Gigabyte AORUS", "SK hynix"], specs: ["500 GB", "1 TB", "2 TB", "4 TB+", "PCIe 3.0", "PCIe 4.0", "PCIe 5.0", "DRAM'li", "DRAM'siz", "7000 MB/s+"] },
  anakart: { name: "Anakart", description: "İşlemci soketi, yonga seti ve kasa boyutuna göre anakartlar.", types: ["AMD AM5", "AMD AM4", "Intel LGA1851", "Intel LGA1700", "ATX", "Micro-ATX", "Mini-ITX", "Overclock Anakartı"], brands: ["ASUS ROG / TUF / Prime", "MSI MPG / MAG / PRO", "Gigabyte AORUS", "ASRock", "Biostar"], specs: ["DDR4", "DDR5", "Wi-Fi 6E", "Wi-Fi 7", "PCIe 5.0", "2.5G LAN", "USB4", "Thunderbolt", "RGB / ARGB Header"] },
  islemci: { name: "İşlemci", description: "Platform, çekirdek sınıfı ve kullanım amacına göre işlemciler.", types: ["AMD Ryzen 5", "AMD Ryzen 7", "AMD Ryzen 9", "AMD X3D", "Intel Core Ultra 5", "Intel Core Ultra 7", "Intel Core Ultra 9", "Intel Core i5 / i7 / i9"], brands: ["AMD", "Intel"], specs: ["6 Çekirdek", "8 Çekirdek", "12 Çekirdek", "16 Çekirdek+", "Dahili Grafik", "Kilit Açık", "Kutulu", "Tray", "AM5", "LGA1851", "LGA1700"] },
  "ram-bellek": { name: "RAM Bellek", description: "Nesil, kapasite ve gecikmeye göre oyuncu bellekleri.", types: ["DDR5", "DDR4", "RGB RAM", "Düşük Profil", "SO-DIMM Laptop", "Tek Modül", "Dual Kit", "Quad Kit"], brands: ["Kingston Fury", "Corsair Vengeance / Dominator", "G.Skill Trident Z / Ripjaws", "Crucial", "TeamGroup T-Force", "ADATA XPG", "Patriot Viper", "Lexar", "Samsung"], specs: ["16 GB", "32 GB", "48 GB", "64 GB", "6000 MT/s+", "CL30 ve altı", "AMD EXPO", "Intel XMP"] },
  "guc-kaynagi": { name: "Güç Kaynağı", description: "Güç, verimlilik ve kablo yapısına göre PSU modelleri.", types: ["Tam Modüler", "Yarı Modüler", "Sabit Kablolu", "SFX", "SFX-L", "ATX"], brands: ["Corsair", "Seasonic", "FSP", "Cooler Master", "be quiet!", "Thermaltake", "MSI", "ASUS ROG / TUF", "Gigabyte", "NZXT", "DeepCool", "XPG"], specs: ["550–650 W", "750–850 W", "1000 W", "1200 W+", "80 PLUS Bronze", "Gold", "Platinum", "Titanium", "ATX 3.0 / 3.1", "12V-2x6"] },
  "sivi-sogutma": { name: "Sıvı Soğutma", description: "Radyatör ölçüsü, ekran ve platform desteğine göre AIO çözümler.", types: ["120 mm", "240 mm", "280 mm", "360 mm", "420 mm", "LCD Ekranlı", "ARGB", "Özel Döngü Bileşeni"], brands: ["Corsair", "NZXT", "Cooler Master", "ASUS ROG", "MSI", "Thermaltake", "Arctic", "DeepCool", "Lian Li", "be quiet!", "Gigabyte AORUS", "FSP", "GameBooster", "Rampage"], specs: ["AM5", "AM4", "LGA1851", "LGA1700", "PWM Pompa", "Değiştirilebilir Fan", "Düşük Gürültü", "5 Yıl+ Garanti"] },
  "hava-sogutma": { name: "Hava Soğutma", description: "Kule yapısı, yükseklik ve TDP kapasitesine göre CPU soğutucular.", types: ["Tek Kule", "Çift Kule", "Low Profile", "Tek Fan", "Çift Fan", "Pasif Soğutucu", "ARGB Hava Soğutucu"], brands: ["Noctua", "be quiet!", "Thermalright", "DeepCool", "Cooler Master", "Arctic", "Scythe", "ID-Cooling", "Thermaltake", "Corsair", "ASUS", "FSP"], specs: ["AM5", "AM4", "LGA1851", "LGA1700", "150 mm altı", "160 mm+", "200 W+ TDP", "Sessiz Fan"] },
  "kasa-fani": { name: "Kasa Fanı", description: "Ölçü, bağlantı, hava akışı ve aydınlatmaya göre kasa fanları.", types: ["120 mm", "140 mm", "200 mm", "Tekli Fan", "2'li Paket", "3'lü Paket", "Ters Kanat", "Slim Fan"], brands: ["Corsair", "NZXT", "Cooler Master", "Lian Li", "Noctua", "Arctic", "be quiet!", "Thermaltake", "Phanteks", "ASUS", "MSI", "DeepCool", "Vento", "Rampage"], specs: ["PWM 4-Pin", "DC 3-Pin", "ARGB", "RGB", "Fansız Aydınlatma", "Yüksek Hava Akışı", "Yüksek Statik Basınç", "Sessiz"] },
  "yayin-ekipmanlari": { name: "Mikrofon ve Yayın", description: "Yayın, kayıt ve görüntü yakalama ekipmanları.", types: ["USB Mikrofon", "XLR Mikrofon", "Mikrofon Kolu", "Ses Kartı / Interface", "Stream Deck", "Capture Card", "Web Kamera", "Işık", "Green Screen"], brands: ["Elgato", "Rode", "Shure", "HyperX", "Logitech", "Blue", "Fifine", "Razer", "SteelSeries", "Focusrite", "AVerMedia", "Maono", "NZXT"], specs: ["USB-C", "XLR", "Kardioid", "Çoklu Polar Pattern", "4K Capture", "1080p60", "Yayıncı Paketi"] },
  "gamepad-joystick": { name: "Gamepad ve Joystick", description: "Platform ve kontrol türüne göre oyun kontrolcüleri.", types: ["PC Gamepad", "PlayStation Kontrolcü", "Xbox Kontrolcü", "Nintendo Kontrolcü", "Mobil Kontrolcü", "Arcade Stick", "Flight Stick"], brands: ["Microsoft Xbox", "Sony DualSense", "Nintendo", "GameSir", "8BitDo", "Razer", "Logitech", "Thrustmaster", "Hori", "Turtle Beach", "SCUF"], specs: ["Kablolu", "Kablosuz", "Hall Effect", "Arka Tuşlu", "Şarj İstasyonlu", "PC", "Konsol", "Mobil"] },
  "direksiyon-seti": { name: "Direksiyon Seti", description: "Tahrik sistemi ve platforma göre sim racing ekipmanları.", types: ["Direksiyon Seti", "Pedal", "Vites", "El Freni", "Wheel Base", "Direksiyon Çemberi", "Kokpit / Stand"], brands: ["Logitech G", "Thrustmaster", "Fanatec", "Moza Racing", "Simagic", "PXN", "Hori", "Turtle Beach"], specs: ["Gear Drive", "Belt Drive", "Direct Drive", "PC", "PlayStation", "Xbox", "2 Pedal", "3 Pedal", "Load Cell"] },
  "oyuncu-koltugu": { name: "Oyuncu Koltuğu", description: "Gövde, döşeme ve ergonomi özelliklerine göre koltuklar.", types: ["Oyuncu Koltuğu", "Ergonomik Fileli", "XL Koltuk", "Kumaş", "Deri", "Bel Destekli", "Ayak Destekli"], brands: ["XDrive", "Hawk", "Rampage", "Cougar", "Corsair", "Razer", "MSI", "ASUS ROG", "AndaSeat", "Secretlab", "Noblechairs", "GamePower"], specs: ["120 kg altı", "120–150 kg", "150 kg+", "4D Kolçak", "Bel Yastığı", "Boyun Yastığı", "Yatar Sırt"] },
  "oyuncu-masasi": { name: "Oyuncu Masası", description: "Setup genişliği ve aksesuarlarına göre oyuncu masaları.", types: ["Düz Masa", "L Masa", "Yükseklik Ayarlı", "Elektrikli Masa", "Karbon Yüzey", "Yayın Masası"], brands: ["XDrive", "Hawk", "Cougar", "GamePower", "Rampage", "Thermaltake", "Secretlab", "IKEA Gaming"], specs: ["120 cm", "140 cm", "160 cm+", "Kablo Kanalı", "Monitör Kolu Uyumlu", "Kulaklık Askısı", "Bardaklık"] },
};
