"use client";
import {useMemo,useState} from "react";
import MarketplaceShell from "@/components/MarketplaceShell";

const steps=["Ürün","Detaylar","Fiyat","Teslimat","Önizleme"];
export default function Page(){
 const [step,setStep]=useState(0); const [title,setTitle]=useState(""); const [category,setCategory]=useState(""); const [condition,setCondition]=useState("Yeni gibi"); const [desc,setDesc]=useState(""); const [price,setPrice]=useState(""); const [increment,setIncrement]=useState("100"); const [reserve,setReserve]=useState(""); const [duration,setDuration]=useState("3 gün"); const [shipping,setShipping]=useState("Satıcı öder");
 const completion=useMemo(()=>[title,category,desc,price].filter(Boolean).length*25,[title,category,desc,price]);
 return <MarketplaceShell eyebrow="SATIŞ MERKEZİ" title="Yeni ilan oluştur" description="Ürününü adım adım hazırla, ön izle ve güvenle açık artırmaya çıkar.">
  <div className="listingTopBar"><div><b>Taslak ilan</b><span>Değişikliklerin otomatik kaydedilir</span></div><div className="completionRing" style={{"--progress":`${completion*3.6}deg`} as React.CSSProperties}><span>{completion}%</span></div></div>
  <div className="listingStepsPremium">{steps.map((s,i)=><button key={s} className={i===step?"active":i<step?"done":""} onClick={()=>setStep(i)}><b>{i<step?"✓":i+1}</b><span>{s}</span></button>)}</div>
  <div className="listingLayoutPremium"><form className="listingFormPremium" onSubmit={e=>e.preventDefault()}>
   {step===0&&<><section className="formSectionPremium"><div className="formSectionHead"><span>01</span><div><h3>Ürün fotoğrafları</h3><p>İlk fotoğraf kapak görseli olarak kullanılır.</p></div></div><label className="uploadZonePremium"><input type="file" multiple accept="image/*"/><div className="uploadIcon">＋</div><strong>Fotoğraf seç veya buraya sürükle</strong><small>En fazla 10 fotoğraf · JPG, PNG · Maksimum 10 MB</small></label><div className="photoSlots">{[1,2,3,4,5].map(x=><span key={x}>Fotoğraf {x}</span>)}</div></section><section className="formSectionPremium"><div className="formSectionHead"><span>02</span><div><h3>Ürününü tanımla</h3><p>Alıcıların aramada kolayca bulabileceği bilgiler gir.</p></div></div><label>İlan başlığı <em>{title.length}/80</em><input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)} placeholder="Örn. iPhone 15 Pro 256 GB Titanyum"/></label><div className="formGridPremium"><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Kategori seç</option><option>Telefon</option><option>Bilgisayar</option><option>Oyun & Konsol</option><option>Saat</option><option>Koleksiyon</option></select></label><label>Ürün durumu<select value={condition} onChange={e=>setCondition(e.target.value)}><option>Sıfır</option><option>Yeni gibi</option><option>İyi</option><option>Kullanılmış</option></select></label></div></section></>}
   {step===1&&<section className="formSectionPremium"><div className="formSectionHead"><span>03</span><div><h3>Ürün detayları</h3><p>Şeffaf açıklama daha fazla güven ve teklif getirir.</p></div></div><label>Açıklama <em>{desc.length}/2000</em><textarea rows={9} maxLength={2000} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Ürünün kullanım durumu, kutu içeriği, garanti bilgisi, varsa kusurları ve tüm önemli detaylar..."/></label><div className="formGridPremium"><label>Marka<input placeholder="Örn. Apple"/></label><label>Model<input placeholder="Örn. iPhone 15 Pro"/></label><label>Garanti<select><option>Garantili</option><option>Garantisiz</option><option>Distribütör garantili</option></select></label><label>Fatura<select><option>Var</option><option>Yok</option></select></label></div></section>}
   {step===2&&<section className="formSectionPremium"><div className="formSectionHead"><span>04</span><div><h3>Açık artırma ayarları</h3><p>Rekabetçi başlangıç fiyatı daha fazla katılım sağlar.</p></div></div><div className="priceHeroInput"><span>Başlangıç teklifi</span><div><b>₺</b><input value={price} onChange={e=>setPrice(e.target.value.replace(/\D/g,""))} placeholder="0"/></div><small>Önerilen: Piyasa değerinin %55–70'i</small></div><div className="formGridPremium"><label>Minimum teklif artışı<input value={increment} onChange={e=>setIncrement(e.target.value)} placeholder="₺ 100"/></label><label>Gizli taban fiyat<input value={reserve} onChange={e=>setReserve(e.target.value)} placeholder="₺ 0"/></label><label>Açık artırma süresi<select value={duration} onChange={e=>setDuration(e.target.value)}><option>24 saat</option><option>3 gün</option><option>7 gün</option><option>10 gün</option></select></label><label>Başlangıç zamanı<select><option>Hemen yayınla</option><option>Tarih planla</option></select></label></div><div className="infoCallout"><b>Gizli taban fiyat nedir?</b><p>Ürünün satılmasını kabul ettiğin en düşük tutardır. Alıcılar bu tutarı görmez.</p></div></section>}
   {step===3&&<section className="formSectionPremium"><div className="formSectionHead"><span>05</span><div><h3>Teslimat ve ödeme</h3><p>Alıcıya sunacağın teslimat yöntemlerini belirle.</p></div></div><div className="deliveryChoices">{["Satıcı öder","Alıcı öder","Elden teslim"].map(x=><button type="button" key={x} onClick={()=>setShipping(x)} className={shipping===x?"active":""}><b>{x}</b><small>{x==="Elden teslim"?"Konum doğrulamalı teslim":"Anlaşmalı kargo ile güvenli gönderim"}</small></button>)}</div><div className="formGridPremium"><label>Kargoya verme süresi<select><option>1 iş günü</option><option>2 iş günü</option><option>3 iş günü</option></select></label><label>Gönderim şehri<select><option>İzmir</option><option>İstanbul</option><option>Ankara</option></select></label></div><div className="securePaymentBox"><span>🛡</span><div><b>Güvenli ödeme otomatik aktif</b><p>Ödeme, alıcı ürünü onaylayana kadar güvenli havuzda tutulur.</p></div></div></section>}
   {step===4&&<section className="formSectionPremium previewSection"><div className="formSectionHead"><span>06</span><div><h3>İlan önizlemesi</h3><p>Yayınlamadan önce tüm bilgileri kontrol et.</p></div></div><div className="listingPreviewCard"><div className="previewImage">ÜRÜN FOTOĞRAFI</div><div><span>{category||"Kategori seçilmedi"}</span><h2>{title||"İlan başlığın burada görünecek"}</h2><p>{desc||"Ürün açıklaman burada görünecek."}</p><div className="previewPrice"><small>Başlangıç teklifi</small><strong>₺{price||"0"}</strong></div><div className="previewFacts"><b>{condition}</b><b>{duration}</b><b>{shipping}</b></div></div></div><label className="approvalCheck"><input type="checkbox"/> İlan bilgilerinin doğru olduğunu ve platform kurallarını kabul ettiğimi onaylıyorum.</label></section>}
   <div className="formActionsPremium"><button type="button" className="ghost" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}>← Geri</button><span>Adım {step+1} / {steps.length}</span>{step<steps.length-1?<button type="button" className="primary" onClick={()=>setStep(step+1)}>Devam et →</button>:<button type="button" className="primary publish">İlanı yayınla</button>}</div>
  </form><aside className="listingTipsPremium"><div className="tipsSticky"><span className="tipBadge">KAPIŞKAPIŞ İPUÇLARI</span><h3>Daha hızlı sat</h3><ul><li><b>Net fotoğraflar</b><small>Farklı açılardan, aydınlık görseller ekle.</small></li><li><b>Şeffaf açıklama</b><small>Kusurları ve kullanım izlerini mutlaka belirt.</small></li><li><b>Doğru fiyat</b><small>Düşük başlangıç daha fazla teklif getirir.</small></li><li><b>Hızlı kargo</b><small>1 iş günü seçen satıcılar daha çok tercih edilir.</small></li></ul><div className="sellerScore"><span>İlan kalite puanı</span><strong>{completion}<small>/100</small></strong><div><i style={{width:`${completion}%`}}/></div></div><div className="supportMini"><b>Yardıma mı ihtiyacın var?</b><p>Satıcı destek ekibimiz her adımda yanında.</p><a href="/yardim">Destek merkezine git →</a></div></div></aside></div>
 </MarketplaceShell>
}
